Format shell scripts using shfmt.

diff --git a/bin/ide b/bin/ide
--- a/bin/ide
+++ b/bin/ide
@@ -5,41 +5,41 @@ set -euo pipefail
 
 # Launch IDE in project directory
 launch() {
-	local ide="$1"
-	local dir="$2"
-	if [[ "${dir}" == "${PWD}" ]]; then
-		dir="."
-	fi
+    local ide="$1"
+    local dir="$2"
+    if [[ "${dir}" == "${PWD}" ]]; then
+        dir="."
+    fi
 
-	command -v "${ide}" &> /dev/null || raise error "IDE not found: ${ide}"
+    command -v "${ide}" &> /dev/null || raise error "IDE not found: ${ide}"
 
-	echo "Launching ${ide} ${dir/"${HOME}"/"~"}"
-	nohup "${ide}" "${dir}" &>/dev/null &
-	exit 0
+    echo "Launching ${ide} ${dir/"${HOME}"/"~"}"
+    nohup "${ide}" "${dir}" &> /dev/null &
+    exit 0
 }
 
 # Read the starting directory
-dir=$( realpath "${1:-${PWD}}" )
+dir=$(realpath "${1:-${PWD}}")
 if [[ ! -d "${dir}" ]]; then
-	echo "Not a directory: $1"
-	exit 1
+    echo "Not a directory: $1"
+    exit 1
 fi
 
 # Scan directories until we encounter $HOME or /
 while [[ "${dir}" != "/" ]]; do
-	if [[ "${dir}" = "${HOME}" ]]; then
-		break
-	fi
-	if [[ -f "${dir}/composer.json" ]]; then
-		launch phpstorm "${dir}"
-	elif [[ -f "${dir}/pyproject.toml" ]]; then
-		launch pycharm "${dir}"
-	elif [[ -f "${dir}/Cargo.toml" ]]; then
-		launch rustrover "${dir}"
-	elif [[ -f "${dir}/README.md" ]] || [[ -f "${dir}/LICENSE" ]]; then
-		launch code "${dir}"
-	fi
-	dir=$( dirname "${dir}" )
+    if [[ "${dir}" = "${HOME}" ]]; then
+        break
+    fi
+    if [[ -f "${dir}/composer.json" ]]; then
+        launch phpstorm "${dir}"
+    elif [[ -f "${dir}/pyproject.toml" ]]; then
+        launch pycharm "${dir}"
+    elif [[ -f "${dir}/Cargo.toml" ]]; then
+        launch rustrover "${dir}"
+    elif [[ -f "${dir}/README.md" ]] || [[ -f "${dir}/LICENSE" ]]; then
+        launch code "${dir}"
+    fi
+    dir=$(dirname "${dir}")
 done
 
 echo "Project directory not found."
